### ISSUE TITLE
ILT0014

### ISSUE THREAD

**Issue by dinrise** [xXPancakeXx/Win10-Explorer#12]
I have error when compiling =(

C:\Users\UserName\.nuget\packages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): error :  ILT0014: Failed to compile interop source code. See the build log for error details.

**Comment by xXPancakeXx** [comment]
Oh I had that error once,  but I can not remember what I did.
Have you tired unchecking the "compile .Net Native toolchain"

![image](https://user-images.githubusercontent.com/22404008/75251813-a66f7c80-57db-11ea-99a3-f77a813fac7b.png)

Also what are your compile settings? 64-Bit debug?
Have you checked the build log for further information?

**Comment by dinrise** [comment]
Okay, i use 64-Bit debug, and check this checkbox, and it's compiled. But cant run app(

**Comment by xXPancakeXx** [comment]
If you want to package it to be able to install it on any device you have to the following:
1. Right click project in solution explorer
2. Click "Publish"
3. Click "Create App Packaging"
4. Choose "Sideloading"
5. Continue the process

Then you will get a folder with all the files you. In it is a powershell file. Execute it.
=> App is installed on your pc

Note that if you run the app in VisualStudio, it be installed aswell and you are able to open it via WindowsSearch

**Comment by dinrise** [comment]
Thank you! You are best! After new commits, building without any problems!

**Comment by ste-phil** [comment]
пожалуйста,

If you have any more questions or want some information about some code section I will be happy to help :)

**Comment by dinrise** [comment]
What you think about add Open Control Panel when click on gear?) And why menu sandwich moving to some pixels down? )

**Comment by ste-phil** [comment]
The gear icon was intended for some settings (e.g. changing hotkeys to different ones, displaying information about the author, changing the color theme etc.) 


![image](https://user-images.githubusercontent.com/22404008/75392027-7fa06b80-58eb-11ea-9f57-6e97a0bac1b9.png)
Do you mean this by sandwich? If yes then I am not responsible for positioning the element not on the top. I used [https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview](this) library element to build the sidebar.

You are more than welcome to contribute to the file explorer if you wish to.
For example things I wanted to do are: 
* Making drag&drop work properly
* Make the grid view usable (its only for the visuals now) :)
* Enable history for any file that you can see where you moved it around
* Make the columns modifiable (e.g hide some colums, make them fit when resizing the window, ...)

I still have a few more ideas, but not enough time :(

**Comment by dinrise** [comment]
Yeah, but https://docs.microsoft.com/ru-ru/uwp/api/windows.ui.xaml.controls.navigationviewbackbuttonvisible
